name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Bazel Action
      uses: ngalaiko/bazel-action@2.0.0
      

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: bazel build //...

    - name: Test
      run: bazel test //...
